name: Add Issues & PRs to Project

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const org = process.env.ORG;
            const projectNumber = Number(process.env.PROJECT_NUMBER);

            const q = `
              query($org: String!, $number: Int!) {
                organization(login: $org) { projectV2(number: $number) { id } }
                user(login: $org) { projectV2(number: $number) { id } }
              }`;

            const result = await github.graphql(q, { org, number: projectNumber });

            const projectId =
              result.organization?.projectV2?.id ??
              result.user?.projectV2?.id;

            if (!projectId) {
              core.setFailed('Project not found. Check ORG and PROJECT_NUMBER.');
              return;
            }

            const contentId = context.payload.issue?.node_id || context.payload.pull_request?.node_id;
            if (!contentId) { console.log("No content ID"); return; }

            const mutation = `
              mutation($project: ID!, $content: ID!) {
                addProjectV2ItemById(input: {projectId: $project, contentId: $content}) {
                  item { id }
                }
              }`;

            await github.graphql(mutation, { project: projectId, content: contentId });
        env:
          ORG: ${{ secrets.ORG }}
          PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}
